# Generated by Django 4.2.5 on 2023-12-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyocr',
            name='languauge',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='file',
            field=models.FileField(null=True, upload_to='ocr/'),
        ),
    ]
