# Generated by Django 4.2.5 on 2023-12-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_dailyocr_languauge_page_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyocr',
            name='file',
            field=models.FileField(null=True, upload_to='ocr/'),
        ),
    ]
