# Generated by Django 4.2.5 on 2023-12-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0003_dailyocr_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyocr',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='ocrresult',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
