# Generated by Django 4.2.5 on 2023-09-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=200)),
                ('published_time', models.DateTimeField()),
                ('source', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('is_positive', models.BooleanField()),
                ('is_latest', models.BooleanField()),
            ],
        ),
    ]
