# Generated by Django 4.2.5 on 2023-10-07 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsgatherers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='youtube_csv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FileField(upload_to='')),
                ('published_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='youtube_csv_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=700)),
                ('views', models.CharField(max_length=200)),
                ('thumbnail', models.CharField(max_length=900)),
                ('link', models.CharField(max_length=800)),
                ('published_time_ago', models.CharField(max_length=200)),
                ('duration_of_video', models.CharField(max_length=200)),
                ('channel_name', models.CharField(max_length=500)),
                ('type_of_platform', models.CharField(max_length=200)),
                ('youtube_csv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsgatherers.youtube_csv')),
            ],
        ),
    ]
