# Generated by Django 4.2.5 on 2023-12-19 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsgatherers', '0002_rename_sentiment_analysis_result_news_cluster_head_sentiment_analysis_result_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='negative_publisher_today',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NEGATIVE', models.CharField(blank=True, max_length=50, null=True)),
                ('publisher', models.CharField(blank=True, max_length=150, null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='news_cluster_head',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 19, 13, 11, 8, 826681, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='news_obj',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 19, 13, 11, 8, 827784, tzinfo=datetime.timezone.utc)),
        ),
    ]
