# Generated by Django 4.2.5 on 2023-12-15 22:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsgatherers', '0002_alter_news_cluster_head_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_cluster_head',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 15, 22, 15, 36, 857420)),
        ),
        migrations.AlterField(
            model_name='news_obj',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 15, 22, 15, 36, 859780, tzinfo=datetime.timezone.utc)),
        ),
    ]
