# Generated by Django 4.2.5 on 2023-10-07 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsgatherers', '0002_youtube_csv_youtube_csv_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube_csv',
            name='data',
            field=models.FileField(upload_to='csv_files/'),
        ),
    ]
