# Generated by Django 4.2.5 on 2023-10-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsgatherers', '0002_youtube'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eprints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
