# Generated by Django 4.2.5 on 2023-10-08 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsgatherers', '0003_alter_youtube_csv_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtube_csv_data',
            name='youtube_csv',
        ),
    ]
