# Generated by Django 4.2.5 on 2023-12-19 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsgatherers', '0003_negative_publisher_today_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negative_publisher_today',
            name='published_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='news_cluster_head',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 19, 13, 15, 38, 943532, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='news_obj',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 19, 13, 15, 38, 945532, tzinfo=datetime.timezone.utc)),
        ),
    ]
