# Generated by Django 4.2.5 on 2023-12-16 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsgatherers', '0004_alter_news_cluster_head_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_cluster_head',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 16, 13, 57, 15, 709139, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='news_obj',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 16, 13, 57, 15, 710139, tzinfo=datetime.timezone.utc)),
        ),
    ]
