# Generated by Django 4.2.5 on 2023-10-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsgatherers', '0004_remove_youtube_csv_data_youtube_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube_csv_data',
            name='channel_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='youtube_csv_data',
            name='duration_of_video',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='youtube_csv_data',
            name='link',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='youtube_csv_data',
            name='published_time_ago',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='youtube_csv_data',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='youtube_csv_data',
            name='title',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='youtube_csv_data',
            name='type_of_platform',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='youtube_csv_data',
            name='views',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
