# Generated by Django 4.2.5 on 2023-10-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsgatherers', '0005_alter_youtube_csv_data_channel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube_csv_data',
            name='video_json_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
