# Generated by Django 4.2.5 on 2023-10-27 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsgatherers', '0003_eprints'),
        ('newsgatherers', '0007_remove_youtube_csv_data_video_json_data'),
    ]

    operations = [
    ]
