# Generated by Django 4.2.5 on 2023-12-08 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsgatherers', '0004_url'),
        ('newsgatherers', '0008_merge_20231027_1839'),
    ]

    operations = [
    ]
