# Generated by Django 4.2.5 on 2023-12-17 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsgatherers', '0009_alter_news_cluster_head_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_cluster_head',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 17, 6, 33, 19, 936521, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='news_cluster_head',
            name='url',
            field=models.URLField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='news_obj',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 17, 6, 33, 19, 938337, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='news_obj',
            name='url',
            field=models.URLField(blank=True, max_length=900, null=True),
        ),
    ]
