# Generated by Django 4.2.5 on 2023-12-09 04:53

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('newsgatherers', '0010_rename_youtube_csv_data_youtube_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube_data',
            name='analyzed_data',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
