# Generated by Django 4.2.5 on 2023-12-10 07:21

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('newsgatherers', '0011_youtube_data_analyzed_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtube_data',
            old_name='analyzed_data',
            new_name='sentiment_analysis',
        ),
        migrations.AddField(
            model_name='youtube_data',
            name='summary_json',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
