# Generated by Django 4.2.5 on 2023-12-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsgatherers', '0011_youtube_data_analyzed_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='news_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=700, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('published_date', models.DateTimeField()),
                ('url', models.URLField()),
                ('publisher', models.CharField(blank=True, max_length=700, null=True)),
                ('published_time_ago', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=500, null=True)),
                ('department', models.CharField(blank=True, max_length=700, null=True)),
                ('positive', models.IntegerField()),
                ('neutral', models.IntegerField()),
                ('negative', models.IntegerField()),
                ('sentiment_analysis_result', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
