# Generated by Django 4.2.5 on 2023-12-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsgatherers', '0012_news_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_data',
            name='published_date',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
