# Generated by Django 4.2.5 on 2023-12-11 13:40

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('newsgatherers', '0012_rename_analyzed_data_youtube_data_sentiment_analysis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='news_cluster_head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('is_latest', models.BooleanField()),
                ('sentiment_report', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='news_cluster_obj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('source_type', models.CharField(choices=[('website', 'website'), ('youtube', 'youtube'), ('others', 'others')], max_length=200)),
                ('source_url', models.CharField(max_length=200)),
                ('published_time', models.DateTimeField()),
                ('is_positive', models.BooleanField()),
                ('is_latest', models.BooleanField()),
                ('views', models.CharField(blank=True, max_length=200, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=900, null=True)),
                ('published_time_ago', models.CharField(blank=True, max_length=200, null=True)),
                ('duration_of_video', models.CharField(blank=True, max_length=200, null=True)),
                ('channel_name', models.CharField(blank=True, max_length=500, null=True)),
                ('type_of_platform', models.CharField(blank=True, max_length=200, null=True)),
                ('sentiment_analysis', jsonfield.fields.JSONField(blank=True, null=True)),
                ('summary_json', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='URL',
        ),
        migrations.DeleteModel(
            name='youtube',
        ),
        migrations.DeleteModel(
            name='youtube_csv',
        ),
        migrations.AddField(
            model_name='news_cluster_head',
            name='cluster_obj',
            field=models.ManyToManyField(to='newsgatherers.news_cluster_obj'),
        ),
    ]
