# Generated by Django 4.2.5 on 2023-12-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsgatherers', '0013_alter_news_data_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_data',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='news_data',
            name='Summary_article',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news_data',
            name='main_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
