# Generated by Django 4.2.5 on 2023-12-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsgatherers', '0014_news_data_image_news_data_summary_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_data',
            name='Image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
