# Generated by Django 4.2.5 on 2023-12-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsgatherers', '0015_news_obj_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_obj',
            name='published_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
