# Generated by Django 4.2.5 on 2023-12-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsgatherers', '0015_alter_news_data_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_data',
            name='negative_sentence',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news_data',
            name='neutral_sentence',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news_data',
            name='positive_sentence',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
