# Generated by Django 4.2.5 on 2023-12-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsgatherers', '0016_alter_news_obj_published_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_obj',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='news_obj',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='news_obj',
            name='source_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='news_obj',
            name='source_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='news_obj',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
