# Generated by Django 4.2.5 on 2023-12-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsgatherers', '0017_news_obj_department_news_obj_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_obj',
            name='is_latest',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='news_obj',
            name='is_positive',
            field=models.BooleanField(default=False),
        ),
    ]
