# Generated by Django 4.2.5 on 2023-12-13 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsgatherers', '0016_news_data_negative_sentence_and_more'),
        ('newsgatherers', '0018_alter_news_obj_is_latest_alter_news_obj_is_positive'),
    ]

    operations = [
    ]
