# Generated by Django 4.2.5 on 2023-12-15 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsgatherers', '0019_merge_20231213_1255'),
    ]

    operations = [
        migrations.DeleteModel(
            name='news_data',
        ),
    ]
