# Generated by Django 4.2.5 on 2023-12-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsgatherers', '0019_rename_sentiment_report_news_cluster_head_sentiment_analysis_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_obj',
            name='published_date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
