# Generated by Django 4.2.5 on 2023-12-14 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsgatherers', '0019_merge_20231213_1255'),
        ('newsgatherers', '0020_alter_news_obj_published_date'),
    ]

    operations = [
    ]
