# Generated by Django 4.2.5 on 2023-12-16 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsgatherers', '0020_delete_news_data'),
        ('newsgatherers', '0021_merge_20231214_1043'),
    ]

    operations = [
    ]
